### ISSUE TITLE
Cookie login does not appear to be working

### ISSUE THREAD

**Issue by Peter200lx** [the-eater/camp-collective#4]
First time running the main script in a few months, and I got the foreboding:
```No user logged in with given cookies```

after copying the latest `document.cookie` from my bandcamp page:
```
$ python -m camp-collective -c "tos_dismissed=X; fan_visits=X; logout=X; BACKENDID=X; download_encoding=X; js_logged_in=X; session=X" download-collection /path/to/backups/ -s progress.json
No user logged in with given cookies
```
I don't have time to dig into this quite yet, but I want to when I get some free time. For now I figured I should post here to see if I'm alone in hitting this issue.

I added a quick `print(f"identities: {data['identities']}")` here:
https://github.com/the-eater/camp-collective/blob/master/camp-collective/bandcamp.py#L45
and have:
```identities: {'partner': False, 'bands': [], 'is_admin': None, 'ip_country_code': 'US', 'fan': None, 'user': None, 'labels': [], 'subscribed_to_page_band': None, 'is_page_band_member': None}```

A quick glance over the rest of the data and I don't see any indication that I'm logged in.

**Comment by the-eater** [comment]
`identity` cookie has been set to HttpOnly so `document.cookie` doesn't retrieve it, does it work if you copy the cookie from the header?

**Comment by Peter200lx** [comment]
```
$ python -m camp-collective -c "client_id=X; identity=X; session=X;" download-collection /path/to/backups/ -s progress.json
Logged in as ...
```
Yup, copying the cookies from the headers of the network inspection view of chrome worked. Seems like this is a case of just updating the README.

**Comment by the-eater** [comment]
well, after _checks notes_ 6 months, I finally updated it. wish there was a better way to do it tho. :/

**Comment by Peter200lx** [comment]
> well, after _checks notes_ 6 months, I finally updated it. wish there was a better way to do it tho. :/

One easier approach I found via https://github.com/impliedchaos/mopidy-bandcamp#authentication for chrome:
` chrome://settings/cookies/detail?site=bandcamp.com`

**Comment by the-eater** [comment]
oh identity is all that's needed? nice

**Comment by the-eater** [comment]
just tested it and it wasn't able to authenticate on `identity` only, so don't know what magic they're invoking
